// Code generated by fixgen, DO NOT EDIT.

package fixture

import (
	"context"
	"math/rand/v2"
	"testing"

	ent_gen "ent-tutorial/ent"

	"github.com/samber/lo"
)

func CreateUser(t *testing.T, db *ent_gen.Client, m ent_gen.User) *ent_gen.User {
	t.Helper()

	tbl := &ent_gen.User{
		ID:   rand.Int64(),
		Name: lo.RandomString(32, lo.AlphanumericCharset),
	}

	if isModified(m.ID) {
		tbl.ID = m.ID
	}
	if isModified(m.Name) {
		tbl.Name = m.Name
	}
	if isModified(m.CreatedAt) {
		tbl.CreatedAt = m.CreatedAt
	}
	if m.UpdatedAt != nil {
		tbl.UpdatedAt = m.UpdatedAt
	}

	createdTbl, err := db.User.Create().
		SetID(tbl.ID).
		SetName(tbl.Name).
		SetUpdatedAt(*tbl.UpdatedAt).
		Save(context.Background())
	if err != nil {
		t.Fatal(err)
	}

	return createdTbl
}
