// Code generated by fixgen, DO NOT EDIT.

package fixture

import (
	"context"
	ent_gen "ent/ent"
	"math/rand/v2"
	"testing"
	"time"

	"github.com/samber/lo"
)

func CreateTodo(t *testing.T, db *ent_gen.Client, m *ent_gen.Todo, opts ...func(*ent_gen.TodoCreate)) *ent_gen.Todo {
	t.Helper()

	tbl := &ent_gen.Todo{
		ID:          rand.Int64(),
		Title:       lo.RandomString(32, lo.AlphanumericCharset),
		Description: lo.RandomString(32, lo.AlphanumericCharset),
		CreatedAt:   time.Now(),
		// UpdatedAt is nillable
		// DoneAt is nillable
	}

	if isModified(m.ID) {
		tbl.ID = m.ID
	}
	if isModified(m.Title) {
		tbl.Title = m.Title
	}
	if isModified(m.Description) {
		tbl.Description = m.Description
	}
	if isModified(m.CreatedAt) {
		tbl.CreatedAt = m.CreatedAt
	}
	if m.UpdatedAt != nil {
		tbl.UpdatedAt = m.UpdatedAt
	}
	if m.DoneAt != nil {
		tbl.DoneAt = m.DoneAt
	}

	builder := db.Todo.Create().
		SetID(tbl.ID).
		SetTitle(tbl.Title).
		SetDescription(tbl.Description).
		SetUpdatedAt(*tbl.UpdatedAt).
		SetDoneAt(*tbl.DoneAt)
	for _, opt := range opts {
		opt(builder)
	}

	createdTbl, err := builder.Save(context.Background())
	if err != nil {
		t.Fatal(err)
	}

	return createdTbl
}
