// Code generated by fixgen, DO NOT EDIT.

package fixture

import (
	"context"
	ent_gen "ent/ent"
	"math/rand/v2"
	"testing"
	"time"

	"github.com/samber/lo"
)

func CreateTodo(t *testing.T, db *ent_gen.Client, m *ent_gen.Todo, opts ...func(*ent_gen.TodoCreate)) *ent_gen.Todo {
	t.Helper()

	tbl := &ent_gen.Todo{
		ID:          rand.Int64(),
		Title:       lo.RandomString(32, lo.AlphanumericCharset),
		Description: lo.RandomString(32, lo.AlphanumericCharset),
		CreatedAt:   time.Now(),
		// UpdatedAt is nillable
		// DoneAt is nillable
	}

	builder := db.Todo.Create()
	if isModified(m.ID) {
		builder = SetID(tbl.ID)
	}
	if isModified(m.Title) {
		builder = SetTitle(tbl.Title)
	}
	if isModified(m.Description) {
		builder = SetDescription(tbl.Description)
	}
	if isModified(m.CreatedAt) {
		builder = SetCreatedAt(tbl.CreatedAt)
	}
	if m.UpdatedAt != nil {
		builder = SetUpdatedAt(*tbl.UpdatedAt)
	}
	if m.DoneAt != nil {
		builder = SetDoneAt(*tbl.DoneAt)
	}
	for _, opt := range opts {
		opt(builder)
	}

	createdTbl, err := builder.Save(context.Background())
	if err != nil {
		t.Fatal(err)
	}

	return createdTbl
}
