// Code generated by fixgen, DO NOT EDIT.

package fixture

import (
	"context"
	"math/rand/v2"
	"testing"

	ent_gen "ent/ent"

	"github.com/samber/lo"
)

func CreateTodo(t *testing.T, db *ent_gen.Client, ovrTbl ent_gen.Todo) *ent_gen.Todo {
	t.Helper()

	tbl := &ent_gen.Todo{
		ID:          rand.Int64(),
		Title:       lo.RandomString(32, lo.AlphanumericCharset),
		Description: lo.RandomString(32, lo.AlphanumericCharset),
	}

	createdTbl, err := db.Todo.Create().
		SetID(tbl.ID).
		SetTitle(tbl.Title).
		SetDescription(tbl.Description).
		SetUpdatedAt(*tbl.UpdatedAt).
		SetDoneAt(*tbl.DoneAt).
		Save(context.Background())
	if err != nil {
		t.Fatal(err)
	}

	return createdTbl
}
