FROM google/cloud-sdk:emulators

RUN \
  gcloud config configurations create emulator \
  && gcloud config set auth/disable_credentials true \
  && gcloud config set project test-project \
  && gcloud config set api_endpoint_overrides/spanner http://0.0.0.0:9020/

ENTRYPOINT [ "sh", "-c", "/google-cloud-sdk/bin/cloud_spanner_emulator/gateway_main --hostname 0.0.0.0 --grpc_port 9010 --http_port 9020"]
